//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InEducation.Server
{
    using System;
    using System.Collections.Generic;
    
    public partial class Задание
    {
        public System.DateTime Дата_выдачи { get; set; }
        public System.DateTime Срок_выполнения { get; set; }
        public string Описание { get; set; }
        public int id_ученика { get; set; }
        public int id_предмета { get; set; }
        public int id_базы_знаний { get; set; }
    
        public virtual База_знаний База_знаний { get; set; }
        public virtual Пользователь Пользователь { get; set; }
        public virtual Предмет Предмет { get; set; }
    }
}
