//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InEducation.Server
{
    using System;
    using System.Collections.Generic;
    
    public partial class Чат
    {
        public int id_пользователя { get; set; }
        public int id_пользователя_отправка { get; set; }
        public System.DateTime Дата_отправки { get; set; }
        public string Текст { get; set; }
    
        public virtual Пользователь Пользователь { get; set; }
        public virtual Пользователь Пользователь1 { get; set; }
    }
}
